version: '3.9'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: supermarket
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  cashier:
    build: ./cashier
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/supermarket
    ports:
      - "8000:8000"  # Cashier Service - UI at http://localhost:8000/ui
    volumes:
      - ./:/app
    command: >
      sh -c "python data/init_db.py && uvicorn cashier.main:app --host 0.0.0.0 --port 8000"

  owner:
    build: ./owner
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/supermarket
    ports:
      - "8001:8000"  # Owner Service - UI at http://localhost:8001/ui
    volumes:
      - ./:/app
    command: >
      uvicorn owner.main:app --host 0.0.0.0 --port 8000

volumes:
  db_data: